#!/bin/bash -ue
shopt -s extglob


ARG="${1:-""}"

case "$ARG" in
    -+([0-9]) )
        exec notelog 'do' search-browse "$(echo "$ARG" | tr -d "-")"
        ;;
    * )
        exec notelog 'do' search -i --color "$@"
        ;;
esac
