#!/bin/sh -ue

# Allows to browse notes with fuzzy search
# Usage: notes

# depends on: https://github.com/junegunn/fzf

exec notelog do list | fzf --preview 'notelog do print {}' --bind 'enter:execute(notelog {})'
