#!/bin/sh -ue

# Allows to browse search results using fuzzy search.
# Usage: noteseach-fzf term1 term2

# depends on: https://github.com/junegunn/fzf

die() {   echo "fatal: $1" && exit "${2-1}" ; }

[ $# -gt 0 ] || die "empty search query"

exec notelog grep "$@" |
    fzf -0 \
        --preview-window 'up,70%' \
        --preview 'notelog print $(echo {} | cut -d":" -f1) | NOTE_NAME="{}" notelog-preview.awk' \
        --bind 'enter:execute(notelog edit $(echo {} | cut -d":" -f1-2))'
